#+TITLE: SICP Exercise 2.2
#+SETUPFILE: ../../export-setup/main-settings.org
#+PROPERTY: header-args :tangle chap02exer02.scm


* Exercise 2.2
:PROPERTIES:
:CUSTOM_ID: exercise
:END:

Consider the problem of representing line segments in a plane.  Each segment is
represented as a pair of points: a starting point and an ending point.  Define a
constructor src_scheme[:exports code]{make-segment} and selectors
src_scheme[:exports code]{start-segment} and src_scheme[:exports
code]{end-segment} that define the representation of segments in terms of
points.  Furthermore, a point can be represented as a pair of numbers: the $x$
coordinate and the $y$ coordinate.  Accordingly, specify a constructor
src_scheme[:exports code]{make-point} and selectors src_scheme[:exports
code]{x-point} and src_scheme[:exports code]{y-point} that define this
representation.  Finally, using your selectors and constructors, define a
procedure src_scheme[:exports code]{midpoint-segment} that takes a line segment
as argument and returns its midpoint (the point whose coordinates are the
average of the coordinates of the endpoints).  To try your procedures, you'll
need a way to print points:

#+ATTR_LATEX: :options morekeywords={define,lambda,if}
#+BEGIN_SRC scheme
  (define (print-point p)
    (newline)
    (display "(")
    (display (x-point p))
    (display ",")
    (display (y-point p))
    (display ")"))
#+END_SRC




* Solution
:PROPERTIES:
:CUSTOM_ID: solution
:END:

** Definition of =point=-related functions
:PROPERTIES:
:CUSTOM_ID: point-functions
:END:

#+ATTR_LATEX: :options morekeywords={define,lambda,if},deletekeywords={abs,gcd}
#+BEGIN_SRC scheme
  (define (make-point x y)
    (cons x y))

  (define (x-point point)
    (car point))

  (define (y-point point)
    (cdr point))

  (define (average-points p1 p2)
    (define (average a b)
      (/ (+ a b) 2.0))
    (make-point (average (x-point p1)
			 (x-point p2))
		(average (y-point p1)
			 (y-point p2))))
#+END_SRC




** Definition of =segment=-related functions
:PROPERTIES:
:CUSTOM_ID: segment-functions
:END:

#+ATTR_LATEX: :options morekeywords={define,lambda,if},deletekeywords={abs,gcd}
#+BEGIN_SRC scheme
  ;; takes two points `start-segment` and `end-segment` as inputs and
  ;; constructions a segment data type
  (define (make-segment start-segment end-segment)
    (cons start-segment end-segment))

  ;; takes a segment `segment` as input and returns the starting point of the
  ;; segment
  (define (start-segment segment)
    (car segment))

  ;; takes a segment `segment` as input and returns the ending point of the
  ;; segment
  (define (end-segment segment)
    (cdr segment))

  ;; finds the midpoint of a segment `segment`
  (define (midpoint-segment segment)
    (midpoint-points (start-segment segment)
		     (end-segment segment)))

  (define (print-segment segment)
    (display "starting:")
    (print-point (start-segment segment))
    (newline)
    (display "ending:")
    (print-point (end-segment segment)))
#+END_SRC




** Test cases
:PROPERTIES:
:CUSTOM_ID: example-usage
:END:

The following are some examples of TODO

#+ATTR_LATEX: :options morekeywords={define,lambda,if},deletekeywords={abs,gcd}
#+BEGIN_SRC scheme
  ;; create a few points
  (define p-0-0 (make-point 0 0))
  (define p-2-6 (make-point 2 6))
  (define p-8-4 (make-point 8 4))

  ;; create a few segments
  (define p-0-0.p-2-6 (make-segment p-0-0 p-2-6))
  (define p-2-6.p-8-4 (make-segment p-2-6 p-8-4))

  ;; print the points
  (print-point p-0-0)
  (print-point p-2-6)
  (print-point p-8-4)

  ;; print the segments
  (print-segment p-0-0.p-2-6)
  (print-segment p-2-6.p-8-4)

  ;; print the average of the points
  (print-point (average-points p-0-0 p-2-6))  ;; (1.,5.)
  (print-point (average-points p-2-6 p-8-4))  ;; (5.,5.)

  ;; print segment midpoints (this is equivalent to the previous commands using
  ;; `average-points`)
  (print-point (midpoint-segment p-0-0.p-2-6))  ;; (1.,5.)
  (print-point (midpoint-segment p-2-6.p-8-4))  ;; (5.,5.)
#+END_SRC
